apiVersion: v1
kind: Secret
metadata:
  name: graphjin-config
  labels:
    {{- include "graphjin.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  dev.yaml:
    {{- toYaml .Values.config | nindent 4 }}